# Generated by Django 2.1.5 on 2019-01-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=48)),
                ('detail', models.CharField(default='', max_length=4096)),
                ('author', models.CharField(default='', max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('last_borrowed', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('out', 'Checked Out')], default='available', max_length=48)),
            ],
        ),
    ]
